### ISSUE TITLE
New window(s) spammed when internet connection dropped

### ISSUE THREAD

**Issue by jogerj** [MrBean355/admiralbulldog-sounds#12]
![image](https://user-images.githubusercontent.com/30559735/73498921-f581e780-43be-11ea-9624-31795773d1b7.png)

It just starts a new window without closing the old one == huge memory leak going on
Had to force quit

The black "frame" around the window is the shadow effect from Windows on top of each other

**Comment by MrBean355** [comment]
Very interesting, thanks for reporting this.
At what point does this happen? As soon as you open the app and the sounds download?

**Comment by MrBean355** [comment]
Okay, I've managed to replicate this problem (by accident 😄). It will be fixed soon in version 1.8.1.
