### ISSUE TITLE
Awesome mod :)

### ISSUE THREAD

**Issue by arjunbalgovind** [MrBean355/admiralbulldog-sounds#15]
This is awesome! Makes dota a million times more fun, especially the discord bot cause people who haven't watch bulldog hear the sounds and are so confused its hilarious. It would be cool to see an option to adjust the "as time goes on" frequency, since it would be fun to have it play sounds more often.
In the Echo Slam mod, is it supposed to not play a the "Skadoosh" sound if it misses heroes?

**Comment by MrBean355** [comment]
Thanks for the kind words @arjunbalgovind! I'm always glad if someone can get some enjoyment out of the project.

> It would be cool to see an option to adjust the "as time goes on" frequency, since it would be fun to have it play sounds more often.

I'll definitely be working on this soon! Also I'll be making the event chances customisable (some of them are fixed at 33% at the moment).

> In the Echo Slam mod, is it supposed to not play a the "Skadoosh" sound if it misses heroes?

I think it is supposed to always play "Skadoosh" for Echo Slam. Did it not work for you?

**Comment by arjunbalgovind** [comment]
I tried it only on demo mode, and it didn't play Skadoosh if there were no heroes hit by Echo.

**Comment by MrBean355** [comment]
Hey @arjunbalgovind, very sorry for the delayed response!
I don't have the arcana so I can't test it out. Would you be keen to help test for me?
