### ISSUE TITLE
Icon modification

### ISSUE THREAD

**Issue by rubyzera** [MrBean355/admiralbulldog-sounds#19]
Hello, first of all i want to congratulate you on make this polished and well-made mod! :) 

So i have a suggestion that i want to be able to customize the mod's icons. For example, with the BKB icon i want to use just the sadKEK image, 
![4](https://user-images.githubusercontent.com/65840302/82744922-35495200-9d55-11ea-9f18-f3a110e5b72e.png)
 IMO it's funnier. Is it possible to add this feature to the app or will it require to mess with the .vpk file?
!f so, can you tell me how?

Thanks in advance!

**Comment by MrBean355** [comment]
Recreated here: https://github.com/MrBean355/admiralbulldog-mod/issues/22
