### ISSUE TITLE
No sounds playing

### ISSUE THREAD

**Issue by PedePanoOriginal** [MrBean355/admiralbulldog-sounds#4]
Hello. I followed the tutorial and successfully installed your program. It installed with no problems but unfortunately, I cant play any sound. I'm using Linux Mint 19.2 so it's maybe something related to the player that it uses to play the sounds, idk. Even when I try to play any sound from the "Change Sounds" option it just doesn't play.
Your program is so cool and I would love to be able to use it in my dota games...

**Comment by PedePanoOriginal** [comment]
I found a solution. Reading the logs I noticed that the problem was related to JavaFX not being found. I searched a bit and I found that, for Linux Mint (and maybe Ubuntu), there's a "openjfx" package that should be installed to bring those libraries.
Again, ty for ur program!

**Comment by MrBean355** [comment]
Thanks for bringing this to my attention @PedePanoOriginal!
Don't suppose you still have the crash log? I would like to investigate a bit more.
The JavaFX runtime is supposed to be bundled with the app, meaning you shouldn't need to download any extra packages.

**Comment by PedePanoOriginal** [comment]
Unfortunately I don't. I even tried to reproduce it again by removing the openjfx but, now it's just working, even without it... LUL. My bad I should have saved it...

**Comment by MrBean355** [comment]
Cool, no worries. Thanks for trying!
