### ISSUE TITLE
Cant find match with this mod due to Valve Anti Cheat 

### ISSUE THREAD

**Issue by JohanObluda** [MrBean355/admiralbulldog-sounds#52]
It seems that due to this mod adding/modifying game files that VAC disable match finding with my games. I have to close the mod, re-validate the local files integrity in order to play.

**Comment by MrBean355** [comment]
Hey @JohanObluda!

Please make sure you're using [version 1.13.3](https://github.com/MrBean355/admiralbulldog-sounds/releases/tag/v1.13.3) or higher, as I made a fix for this issue after the Dota patch that caused the issue. Please try it out and let me know if it still gives issues.

Thanks for using the app, hope you're enjoying it!

**Comment by JohanObluda** [comment]
Thank you it works now :)
